name: CI Lint for test_ai.cpp

on:
  push:
    paths:
      - 'test_ai.cpp'
  workflow_dispatch:

jobs:
  cpplint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cpplint
        run: |
          python3 -m pip install --upgrade pip
          pip install cpplint

      - name: Run cpplint (filtered rules to reduce false positives)
        run: |
          cpplint --filter=-legal/copyright,-whitespace/braces,-whitespace/indent,-runtime/references test_ai.cpp
